### ISSUE TITLE
H2R html stripping not working

### ISSUE THREAD

**Issue by emanspeaks** [steveseguin/social_stream#129]
I am using with H2R.  I first enabled H2R globally and went to the global Visibility settings to enable "strip HTML."  However, messages forwarded to H2R still have HTML embedded in them.

If I open a dock session with the &h2r= option an the &striphtml option in the URL, now messages selected in the dock are forwarded to H2R with the correct HTML stripping.

Is this a user problem with how I'm configuring the global settings incorrectly?  Or is there a bug with the global strip HTML option?  For now, I can just use the dock window to forward sanitized messages as needed.

**Comment by steveseguin** [comment]
Thank you for the issue report.

I took a look and I'm not entirely I know where the issue is at the moment.

I already had the global-post-to-h2r option stripping all messages of HTML, but didn't have this h2r strip check added to the &h2r output on the dock version. I added the stripper there also just now, so when using the dock + h2r, it should auto-strip messages you select there, regardless of the stripHTML flags.

That said, this secondary html stripper shouldn't be needed if the global html stripper was working correctly. I've tested it with Twitch chat and it seemed to be working as expected there, so it might be another site that's the issue.

**What chat source are you using to trigger this issue with?**  It might be a site specific issue I'll need to fix.  Thank you

**Comment by emanspeaks** [comment]
I’m having trouble with both Facebook and Twitch. Users with comments that have apostrophes in them are printing the apostrophe hex code in H2R, but do not when pushing through the doc with &striphtml. Since it wasn’t one site but two I suspected a global issue and not site specific.

**Comment by steveseguin** [comment]
Thank you, that's helpful.,

**Comment by steveseguin** [comment]
So I pushed some new code out. You'd need to download it though.

**Comment by emanspeaks** [comment]
Just tested and it works! Excellent.  Thank you!  Closing.

**Comment by steveseguin** [comment]
new problem?

**Comment by emanspeaks** [comment]
Reopening.  I swear I tested this after you pushed the new version this weekend and H2R worked fine.  Today, though, everything was back to the way it was before.  I updated to the latest version not long before my stream, and then during the stream all the comments had HTML gobbledygook in H2R.  I just pressed with it as is rather than doing the pingpong of a page with &striphtml and and another with the H2R controls, heh, but i'd prefer to not go on air with those...

**Comment by steveseguin** [comment]
I pushed another change. Fingers crossed; sorry for this issue. Thank you for re-opening.

![image](https://github.com/steveseguin/social_stream/assets/2575698/8c41c3dd-a6c2-497b-b7ae-dc4e5ac1d9f1)

![image](https://github.com/steveseguin/social_stream/assets/2575698/6dd27c86-59e0-479e-8102-50fe7fcedd6b)

![image](https://github.com/steveseguin/social_stream/assets/2575698/3396aa90-bc88-4b2f-9f85-432c26d7e74f)
