### ISSUE TITLE
When users are chatting in a livespace stream, chat messages appear twice.

### ISSUE THREAD

**Issue by GregSaintJean** [steveseguin/social_stream#140]
Hi. This chrome plugin is really good and I use it all the time. A problem has only came up recently that you might want to take a look at. When I type into the chat window on a stream when streaming on livespace, the chat message appears twice instead of once

**Comment by steveseguin** [comment]
Make sure livespace isn't opened twice, in two tabs, for example.   The publisher window and a guest view window, for example, both might count.

If using Vivaldi browser, make sure dual-mode isn't enabled.

**Comment by steveseguin** [comment]
![image](https://github.com/steveseguin/social_stream/assets/2575698/a1ccc9a2-1281-4749-8a72-22a86409ccc6)
Things seem to work here in my testing, and commonly duplicate messages is two tabs or vivaldi.

If you still can't get it working, there's a toggle option for preventing duplicate messages that 'might' help solve the issue also.

Thank you kindly.

**Comment by steveseguin** [comment]
If the issue is sending a message INTO live space, being the issue, I'll try to take a look and fix.

**Comment by GregSaintJean** [comment]
I used the toggle option for preventing duplicate messages and it works. Thank you! 🙂

**Comment by LuckyLootTube** [comment]
@steveseguin when I am multi streaming and I am typing a message through OBS chat dock (which is the social stream link) the message is sent as many times as live chats I have on.
For example, imagine I am streaming a live giveaway on Facebook, Youtube, Twitch, and Kick, and I Pop-Out all the chats so I can have them in the Social Stream dock in OBS. Then, if I get a message on YouTube and I am typing it from my OBS dock, then that message will be send 4 times (once for Facebook, once for Youtube, once for Twitch and once for Kick).

The problem is that this takes a lot of space from the chat overlay window and it looks goofy because I am sending the same message 4 times.

Is there anything already that it's avoiding this to happen and I don't know how to use it or you are aware of this thing already?
