### ISSUE TITLE
Filter out duplicate emotes dont working in emote wall

### ISSUE THREAD

**Issue by bloodsinc** [steveseguin/social_stream#143]
Hello, when im use the emote wall, and set filter out duplicate emotes it doing nothing, example - when u use 1 emotes or 5 or 10 same emotes it needs to bounce 1 only emote, but anyway it appear all emotes like 5 or 10 instead of 1 same emotes

**Comment by steveseguin** [comment]
![image](https://github.com/steveseguin/social_stream/assets/2575698/a1326b76-f3c6-4b9d-bf01-73c199c65a7f)

This is the toggle you enabled? If you enable it, you will need to open the emotes.html link again, as the URL was updated with the setting.

If enabled, it should show only one type of emoji per message.

If you write two messages, each with the same emoji, it will show the same emoji twice.

I'm not able to see a problem in my testing; it seems to work as expected using youtube emotes.  If you'd like a new feature added, that allows for only one emote type per window (rather than per message), I can look into that.

**Comment by bloodsinc** [comment]
> ![image](https://user-images.githubusercontent.com/2575698/276005668-a1326b76-f3c6-4b9d-bf01-73c199c65a7f.png)
> 
> This is the toggle you enabled? If you enable it, you will need to open the emotes.html link again, as the URL was updated with the setting.
> 
> If enabled, it should show only one type of emoji per message.
> 
> If you write two messages, each with the same emoji, it will show the same emoji twice.
> 
> I'm not able to see a problem in my testing; it seems to work as expected using youtube emotes. If you'd like a new feature added, that allows for only one emote type per window (rather than per message), I can look into that.

Yes toggle enabled, but if this toggle enabled and im use 12 emoji , 4 different types for 4 emojix like 4x4 it appears all 12 emoji and full of 4x4, i think this toggle will be set a maximum of 1 emoji per 1 type, like prevent some spam, but now this toggle doing nothing, dont see any changes after use it )

**Comment by steveseguin** [comment]
To confirm, you sent 1 message? not 4 messages?

**Comment by bloodsinc** [comment]
> To confirm, you sent 1 message? not 4 messages?

Yes , for example i can send 5x2 different emotes and it all appers ( try with twitch and 7tv emotes) , no matter enable or disable the toggle ( i know that i need re enter url )

**Comment by steveseguin** [comment]
Okay, thank you.  7TV emotes do break things.  Normal emojis don't.

I'll fix.

**Comment by steveseguin** [comment]
I pushed a change.  Tested it with 7TV; seems to work, but please let me know either way.

Just refresh the emotes.html page.

**Comment by bloodsinc** [comment]
> I pushed a change. Tested it with 7TV; seems to work, but please let me know either way.
> 
> Just refresh the emotes.html page.

Thx, its working properly now, fastest fix ever )

**Comment by bloodsinc** [comment]
thx
