### ISSUE TITLE
Linux Build Not Launching. 

### ISSUE THREAD

**Issue by TheRealFame** [steveseguin/social_stream#299]
Hello hello! Yes, I did see the issue showing you only made the linux build due to being asked, And i am glad. But! It doesn't launch for the user. So i would like to ask if you can try editing some stuff that make it compatible!

(Can still be ran through wine.)

**Comment by steveseguin** [comment]
https://github.com/steveseguin/social_stream/releases/tag/0.1.50

i've been releasing linux versions with most releases for the last month or two I think

Version 0.1.50 doesn't run?

Are you using ARM, Intel/AMD?  What linux?  ty

**Comment by steveseguin** [comment]
does any version i have run?

**Comment by TheRealFame** [comment]
I use the app image version listed! With an amd CPU/GPU. X86, I hadn't run it with terminal so I didn't get any errors! Also don't forget you'll need to use fallback fonts if not already.

**Comment by steveseguin** [comment]
I installed a fresh Ubuntu system and things worked fine.  I didn't need to run it via terminal; I just double clicked it.

HOWEVER, you need to setup support for AppImages first, otherwise nothing will happen.

![image](https://github.com/user-attachments/assets/5a722067-ccfe-4ea1-ba18-3df33197e6ec)

If having issues, make sure you have FUSE installed; I followed this guide for Ubuntu 24.04 and it worked fine:

https://github.com/appimage/appimagekit/wiki/fuse

You also need to ensure that the AppImage is set to be an executable.

![image](https://i.sstatic.net/hWTb4.gif)

That's it. If it still fails to work, I'm not sure I'm capable of helping as I am not a Linux expert.

**Comment by TheRealFame** [comment]
![image](https://github.com/user-attachments/assets/e375d68a-d7ac-4d13-8876-520dc2464322)
Fuse is installed! (Before doing this.) Just had to check what terminal was gonna say!
Seems like an error i won't be able to understand-

**Comment by steveseguin** [comment]
`apt-get install fuse` didnt' solve that issue for me.

I had to use the instructions here: https://github.com/appimage/appimagekit/wiki/fuse

```
sudo add-apt-repository universe
sudo apt install libfuse2t64
```
For example

**Comment by TheRealFame** [comment]
![image](https://github.com/user-attachments/assets/9a7698f4-8918-4c31-9f2a-9798ecf60111)
Alright, Back. Tried to figure out why r2modman wasn't working! It's something else I would doubt you heard of. It seems like I need to run files with this argument for some reason-? Though that reasoning doesn't make sense to me..

(Linux Distro Akin To Ubuntu 24.04.)

**Comment by steveseguin** [comment]
- I installed fuse, with the method I mentioned
- I right clicked and set the app to be Executable

To run, I right-clicked on the AppImage, and clicked  "Run"

Opened fine.

I was getting the error you mentioned when I didn't have the correct Fuse installed.

I'm not sure what to say.  I don't use Ubuntu desktop as I find it infuriating to use.

**Comment by TheRealFame** [comment]
![image](https://github.com/user-attachments/assets/c34f27bd-339f-4fa6-8e37-e07184bfdd65)
I had the package installed myself for awhile! It seems flathub with ubuntu 24.04 is just breaking compatibility with alot of stuff.
